name : Metrics 
on :
  schedule : [{cron: "30 * * * *"}]
  workflow_dispatch :
  push : {branches: ["master", "main"]}

jobs :
  github-metrics :
    runs-on : ubuntu-latest
    permissions :
      contents : write
    steps :
      - uses : lowlighter/metrics@latest
        with :
          token : ${{ secrets.METRICS_TOKEN }}

          # config
          user : mayli4
          base : header, activity, repositories
          base_indepth : yes
          config_octicon : yes
          config_timezone : America/Michigan

          # achievements
          
          plugin_achievements : yes
          plugin_achievements_display : compact
          plugin_achievements_secrets : yes
          plugin_achievements_threshold : C
